### ISSUE TITLE
kernel image not aligned on 64K boundary (uboot via m1n1)

### ISSUE THREAD

**Issue by juliosueiras** [AsahiLinux/m1n1#106]
![mac-m1](https://user-images.githubusercontent.com/3680302/133329706-1112f92d-e2d0-48c6-a0e9-3091d79fbee4.png)

Hi, I am experimenting with uboot + nixos and wondering if this issue is related to m1n1 or uboot

**Comment by juliosueiras** [comment]
Correction: the u-boot part is fine, the error occur during grub boot

**Comment by marcan** [comment]
I'm confused; you say you're using grub, but that screenshot shows the EFI stub. Are you booting the kernel as an EFI application instead of as a native ARM64 kernel from GRUB?

We aren't really testing with GRUB yet, so various things might be broken... though this sounds like a bug in downstream components, not m1n1.

**Comment by juliosueiras** [comment]
yea, thanks for response
